title: Jhanvi Patel
logo: /assets/img/profile_pic.jpg
description: Software QA Engineer | Data Engineer | Python, QA Tesring, AR/VR, Statistics, AWS, ML Algorithms, Deep learning, AI Models.
#show_downloads: true
theme: jekyll-theme-minimal

