title: Jhanvi Patel
logo: /assets/img/profile_pic.jpg
description: Data Engineer | Embedded Systems | Python, Statistics, AWS, ML Algorithms, Deep learning, AI Models.
#show_downloads: true
theme: jekyll-theme-minimal

